<?php

/*
chat record structure:

chat : {
    chat_guid: <GUID generated by client> <PK>,
	chat_start: mongo date,
	messages: [
      {
        timestamp: mongo date,
        text: chat text,
        isCode: flag true if text should be highlighted
      }
	]
}

 */


$m = new Mongo();
$db = $m->chatServer;
$collection = $db->chats;
$ts = new MongoDate();


if (isset($_POST['chatId']) && $_POST['chatId'] !== 'undefined'){
	$push = true;
	$chatId = $_POST['chatId'];
} else {
	$push = false;
	require_once('ChatId.php');
	$chatId = ChatId::getId();
}

$message = array(
	'text' => $_POST['text'],
	'isCode' => $_POST['isCode'],
	'timestamp' => $ts,
	'username' => $_POST['username']
);

if ($push){
	$collection->update(array('_id' => $chatId), array('$push' => array('messages' => $insert)));
} else {
	$insert = array(
		'_id' => $chatId,
		'chat_start' => $ts,
		'messages' => array($message)
	);
	$collection->insert($insert);
}

echo json_encode(array(
	'text' => $_POST['text'],
	'isCode' => $_POST['isCode'],
	'timestamp' => date('Y-M-d h:i:s', $ts->sec),
	'chatId' => $chatId
));